export enum AppRoute {
  Css = '/Myself-education/css-help',
  Html = '/Myself-education/html-help',
  Js = '/Myself-education/js-help',
  Json = '/Myself-education/json-help',
  Main = '/Myself-education',
  NotFound = '/not-found-screen',
  Sql = '/Myself-education/sql-help',
  Ts = '/Myself-education/ts-help',
  CodePen = '/Myself-education/code-pen-screen',
  Developing = '/Myself-education/developing-help-screen',
  ProgLangsCollection = '/Myself-education/prog-langs-collection',
  Python = '/Myself-education/python-help',
  JsArraysMethods = '/Myself-education/js-arrays-methods-screen',
}
