export enum AppRoute {
  Css = '/css-help',
  Html = '/html-help',
  Js = '/js-help',
  Json = '/json-help',
  Main = '/Myself-education',
  NotFound = '/not-found-screen',
  Sql = '/sql-help',
  Ts = '/ts-help',
  CodePen = '/code-pen-screen',
  Developing = '/developing-help-screen',
  ProgLangsCollection = 'prog-langs-collection',
  Python = '/python-help',
  JsArraysMethods = '/js-arrays-methods-screen',
}
